"""Real Init

Revision ID: 1e29b37b56f1
Revises: 7759371740cc
Create Date: 2018-06-20 15:32:13.760725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e29b37b56f1'
down_revision = '7759371740cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('video_release_date', sa.Date(), nullable=True),
    sa.Column('old_imdb_url', sa.String(length=1000), nullable=True),
    sa.Column('category_action', sa.Boolean(), nullable=False),
    sa.Column('category_adventure', sa.Boolean(), nullable=False),
    sa.Column('category_animation', sa.Boolean(), nullable=False),
    sa.Column('category_children', sa.Boolean(), nullable=False),
    sa.Column('category_comedy', sa.Boolean(), nullable=False),
    sa.Column('category_crime', sa.Boolean(), nullable=False),
    sa.Column('category_documentary', sa.Boolean(), nullable=False),
    sa.Column('category_drama', sa.Boolean(), nullable=False),
    sa.Column('category_fantasy', sa.Boolean(), nullable=False),
    sa.Column('category_flim_noir', sa.Boolean(), nullable=False),
    sa.Column('category_horror', sa.Boolean(), nullable=False),
    sa.Column('category_musical', sa.Boolean(), nullable=False),
    sa.Column('category_mystery', sa.Boolean(), nullable=False),
    sa.Column('category_romance', sa.Boolean(), nullable=False),
    sa.Column('category_sci_fi', sa.Boolean(), nullable=False),
    sa.Column('category_thriller', sa.Boolean(), nullable=False),
    sa.Column('category_war', sa.Boolean(), nullable=False),
    sa.Column('category_western', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_key'), 'item', ['key'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_index(op.f('ix_item_release_date'), 'item', ['release_date'], unique=False)
    op.create_index(op.f('ix_item_year'), 'item', ['year'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fullname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_item_year'), table_name='item')
    op.drop_index(op.f('ix_item_release_date'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_key'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
