"""Add Price

Revision ID: 23017a75f304
Revises: bd3fd4ff113c
Create Date: 2018-06-24 17:52:18.650911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23017a75f304'
down_revision = 'bd3fd4ff113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apple_movie', sa.Column('price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_apple_movie_price'), 'apple_movie', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apple_movie_price'), table_name='apple_movie')
    op.drop_column('apple_movie', 'price')
    # ### end Alembic commands ###
