"""Price None

Revision ID: 2bed4d8c1a5d
Revises: 52dfcf03e9ad
Create Date: 2018-06-25 07:38:35.486109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bed4d8c1a5d'
down_revision = '52dfcf03e9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_item_price'), 'item', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_price'), table_name='item')
    op.drop_column('item', 'price')
    # ### end Alembic commands ###
