"""add rotten movie model'


Revision ID: 4c9952ae0892
Revises: 510a0cfe041a
Create Date: 2018-06-20 17:19:48.909164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9952ae0892'
down_revision = '510a0cfe041a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotten_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('data', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotten_movie_name'), 'rotten_movie', ['name'], unique=False)
    op.create_index(op.f('ix_rotten_movie_url'), 'rotten_movie', ['url'], unique=False)
    op.create_index(op.f('ix_rotten_movie_year'), 'rotten_movie', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rotten_movie_year'), table_name='rotten_movie')
    op.drop_index(op.f('ix_rotten_movie_url'), table_name='rotten_movie')
    op.drop_index(op.f('ix_rotten_movie_name'), table_name='rotten_movie')
    op.drop_table('rotten_movie')
    # ### end Alembic commands ###
