"""Amazon Movie column edit

Revision ID: 52dfcf03e9ad
Revises: ed501364397f
Create Date: 2018-06-25 06:17:39.032238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52dfcf03e9ad'
down_revision = 'ed501364397f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_movie', sa.Column('hd_buy_price', sa.Float(), nullable=True))
    op.add_column('amazon_movie', sa.Column('hd_rent_price', sa.Float(), nullable=True))
    op.add_column('amazon_movie', sa.Column('sd_buy_price', sa.Float(), nullable=True))
    op.add_column('amazon_movie', sa.Column('sd_rent_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_amazon_movie_hd_buy_price'), 'amazon_movie', ['hd_buy_price'], unique=False)
    op.create_index(op.f('ix_amazon_movie_hd_rent_price'), 'amazon_movie', ['hd_rent_price'], unique=False)
    op.create_index(op.f('ix_amazon_movie_sd_buy_price'), 'amazon_movie', ['sd_buy_price'], unique=False)
    op.create_index(op.f('ix_amazon_movie_sd_rent_price'), 'amazon_movie', ['sd_rent_price'], unique=False)
    op.drop_index('ix_amazon_movie_buy_hd_price', table_name='amazon_movie')
    op.drop_index('ix_amazon_movie_buy_sd_price', table_name='amazon_movie')
    op.drop_index('ix_amazon_movie_rent_hd_price', table_name='amazon_movie')
    op.drop_index('ix_amazon_movie_rent_sd_price', table_name='amazon_movie')
    op.drop_column('amazon_movie', 'buy_hd_price')
    op.drop_column('amazon_movie', 'buy_sd_price')
    op.drop_column('amazon_movie', 'rent_sd_price')
    op.drop_column('amazon_movie', 'rent_hd_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_movie', sa.Column('rent_hd_price', mysql.FLOAT(), nullable=True))
    op.add_column('amazon_movie', sa.Column('rent_sd_price', mysql.FLOAT(), nullable=True))
    op.add_column('amazon_movie', sa.Column('buy_sd_price', mysql.FLOAT(), nullable=True))
    op.add_column('amazon_movie', sa.Column('buy_hd_price', mysql.FLOAT(), nullable=True))
    op.create_index('ix_amazon_movie_rent_sd_price', 'amazon_movie', ['rent_sd_price'], unique=False)
    op.create_index('ix_amazon_movie_rent_hd_price', 'amazon_movie', ['rent_hd_price'], unique=False)
    op.create_index('ix_amazon_movie_buy_sd_price', 'amazon_movie', ['buy_sd_price'], unique=False)
    op.create_index('ix_amazon_movie_buy_hd_price', 'amazon_movie', ['buy_hd_price'], unique=False)
    op.drop_index(op.f('ix_amazon_movie_sd_rent_price'), table_name='amazon_movie')
    op.drop_index(op.f('ix_amazon_movie_sd_buy_price'), table_name='amazon_movie')
    op.drop_index(op.f('ix_amazon_movie_hd_rent_price'), table_name='amazon_movie')
    op.drop_index(op.f('ix_amazon_movie_hd_buy_price'), table_name='amazon_movie')
    op.drop_column('amazon_movie', 'sd_rent_price')
    op.drop_column('amazon_movie', 'sd_buy_price')
    op.drop_column('amazon_movie', 'hd_rent_price')
    op.drop_column('amazon_movie', 'hd_buy_price')
    # ### end Alembic commands ###
