"""RottenMovie add columns
'


Revision ID: 60dd503aa24b
Revises: fdacae9b58ac
Create Date: 2018-06-24 16:48:54.625844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dd503aa24b'
down_revision = 'fdacae9b58ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
