"""Add Amazon Movie'


Revision ID: 9c85ef82c3a7
Revises: 23017a75f304
Create Date: 2018-06-24 18:39:19.272991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c85ef82c3a7'
down_revision = '23017a75f304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=True),
    sa.Column('web_page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['web_page_id'], ['web_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amazon_movie_url'), 'amazon_movie', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amazon_movie_url'), table_name='amazon_movie')
    op.drop_table('amazon_movie')
    # ### end Alembic commands ###
