"""Add url column to apple movie'


Revision ID: bd3fd4ff113c
Revises: 827158b6b936
Create Date: 2018-06-24 17:27:03.432474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3fd4ff113c'
down_revision = '827158b6b936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apple_movie', sa.Column('url', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_apple_movie_url'), 'apple_movie', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apple_movie_url'), table_name='apple_movie')
    op.drop_column('apple_movie', 'url')
    # ### end Alembic commands ###
