"""Amazon Movie column add

Revision ID: ed501364397f
Revises: 1bdd0c54c957
Create Date: 2018-06-25 06:12:39.895954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed501364397f'
down_revision = '1bdd0c54c957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_movie', sa.Column('buy_hd_price', sa.Float(), nullable=True))
    op.add_column('amazon_movie', sa.Column('buy_sd_price', sa.Float(), nullable=True))
    op.add_column('amazon_movie', sa.Column('rent_hd_price', sa.Float(), nullable=True))
    op.add_column('amazon_movie', sa.Column('rent_sd_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_amazon_movie_buy_hd_price'), 'amazon_movie', ['buy_hd_price'], unique=False)
    op.create_index(op.f('ix_amazon_movie_buy_sd_price'), 'amazon_movie', ['buy_sd_price'], unique=False)
    op.create_index(op.f('ix_amazon_movie_rent_hd_price'), 'amazon_movie', ['rent_hd_price'], unique=False)
    op.create_index(op.f('ix_amazon_movie_rent_sd_price'), 'amazon_movie', ['rent_sd_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_amazon_movie_rent_sd_price'), table_name='amazon_movie')
    op.drop_index(op.f('ix_amazon_movie_rent_hd_price'), table_name='amazon_movie')
    op.drop_index(op.f('ix_amazon_movie_buy_sd_price'), table_name='amazon_movie')
    op.drop_index(op.f('ix_amazon_movie_buy_hd_price'), table_name='amazon_movie')
    op.drop_column('amazon_movie', 'rent_sd_price')
    op.drop_column('amazon_movie', 'rent_hd_price')
    op.drop_column('amazon_movie', 'buy_sd_price')
    op.drop_column('amazon_movie', 'buy_hd_price')
    # ### end Alembic commands ###
